Doc: Clarify troubleshooting for missing MIB
logstash-plugins/logstash-input-snmp pull request #117
Opened 2023-07-14 15:34 UTC by karenzone

Fixes: #116

Adds headings and tweaks formatting to better clarity

<img width="1279" alt="Screen Shot 2023-07-14 at 9 52 12 AM" src="https://github.com/logstash-plugins/logstash-input-snmp/assets/35154725/b69fd2ee-8a86-440f-a4f5-d7a0124af0d9">

2023-07-18 08:07 UTC, geekpete commented
One minor nitpick but otherwise LGTM and your rewording/restructure greatly increases readability and ease of understanding I think.

2023-07-18 23:07 UTC, geekpete requested changes

2023-07-18 23:46 UTC, karenzone commented on docs/index.asciidoc
> +As `smidump` looks for mib dependencies in its pre-configured path lists as defined in the documentaion in the https://www.ibr.cs.tu-bs.de/projects/libsmi/smi_config.html["MODULES LOCATIONS"] section
```suggestion
The `smidump` function looks for mib dependencies in its pre-configured path lists.
See the "MODULE LOCATIONS" section of the https://www.ibr.cs.tu-bs.de/projects/libsmi/smi_config.html[smi_config documentation] for more info. 
```

2023-07-19 00:09 UTC, geekpete approved these changes

2023-07-19 00:58 UTC, karenzone reviewed
Builds cleanly and renders as expected.

2023-07-19 00:59 UTC, merged